/* SUBCONSULTAS: SON CONSULTAS QUE SE EJECUTAN DENTRO DE OTAS. 
CONSISTE EN UTILIZAR LAS RESULTADOS DE LA SUBCONSULTA PARA OPERAR EN LA CONSULTA PRINCIPAL
Esto se puede hacer gracias a la clave foraneas.
*/
# SACAR USUARIO CON ENTRADA #
SELECT * FROM usuarios WHERE IN(SELECT usuario_id FROM posts);

# SACAR LOS USUARIOS QUE TENGAN ALGUNA ENTRADA QUE EN SU TITULO HABLE DE GTA #
SELECT nombre, apellidos FROM usuarios WHERE id IN (SELECT usuario_id FROM posts WHERE titulo LIKE "%GTA%");

# SACAR TODAS LAS ENTRADAS DE LA CATEGORIA ACCION UTILIDANDO SU NOMBRE #

SELECT titulo FROM posts WHERE categoria_id IN (SELECT ID FROM categorias WHERE nombre = 'Acción');
    
# MOSTRAR LAS CATEGORIAS CON MAS DE 3 ENTRADAS #
SELECT nombre FROM categorias WHERE 
        (SELECT  categoria_id COUNT FROM posts GROUP BY categoria_id  COUNT(categoria_id)>=2);
# MOSTRAR LOS USUARIOS QUE CREARON UNA ENTRADA UN MARTES #

# MOSTRAR EL NOMBRE DEL USUARIO QUE TENGA MAS ENTRADAS #
SELECT nombre FROM usuarios WHERE id IN
        (SELECT COUNT(id) usuario_id, FROM entradas GROUP BY usuario_id
# MOSTRAR LAS CATEGORIAS SIN ENTRADAS #