# MOSTRAR TODOS LOS REGISTROS DE UNA TABLA #
SELECT email,apellidos FROM usuarios;

# MOSTRAR TODOS LOS CAMPOS #
SELECT * FROM usuarios;

# OPERADORES ARITMETICOS #
SELECT email,(7+7) AS 'OPERACION' FROM usuarios;

# FUNCIONES MATAMATICAS #
SELECT ABS(7) AS 'OPERACION' FROM usuarios;
SELECT CEIL(7.34) AS 'OPERACION' FROM usuarios;
SELECT FLOOR(7.34) AS 'OPERACION' FROM usuarios;
SELECT RAND() AS 'OPERACION' FROM usuarios;
SELECT ROUND(7.12 7) AS 'OPERACION' FROM usuarios;
SELECT SQRT(7.12 7) AS 'OPERACION' FROM usuarios;